[workspace]
resolver = "3"
members = ["services/gateway", "services/identity"]

[workspace.package]
version = "0.1.0"

[workspace.metadata.crane]
name = "home-ryanseipp"

[workspace.dependencies]
tonic = "0.14"
tonic-prost = "0.14"
prost = "0.14"
prost-types = "0.14"
tonic-prost-build = "0.14"
